version: '3.8'

services:
  app:
    build: .
    container_name: ww-producoes-app
    restart: always
    ports:
      - "3001:3001"
    volumes:
      # Mapeia a pasta ./data da VPS para dentro do contentor
      # Garante que a base de dados SQLite não é apagada ao atualizar a app
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3001
